name: Build,Analyze,scan

on:
  push:
    branches:
      - main


jobs:
  build-analyze-scan:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: Log in to DockerHub
        run: |
         echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
           -u "${{ secrets.DOCKERHUB_USERNAME }}" \
           --password-stdin

      - name: Build and push
        run: |
         docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe:latest" .
         docker push "${{ secrets.DOCKERHUB_USERNAME }}/tic-tac-toe:latest"
        
      - name: Trivy file scan
        run: trivy fs . > trivyfs.txt

  deploy:
   needs: build-analyze-scan   
   runs-on: [self-hosted]
   steps:
      - name: docker pull image
        run: docker pull ayolannister/tic-tac-toe:latest

      - name: Image scan
        run: trivy image ayolannister/tic-tac-toe:latest > trivyimagedeploy.txt  
  
      - name: Deploy to container
        run: docker run -d --name game -p 3000:3000 ayolannister/tic-tac-toe:latest

      - name: Update kubeconfig
        run: |
          az aks get-credentials \
            --resource-group aks-cloud-rg \
            --name AKS-CLOUD \
            --overwrite-existing

      - name: Verify AKS connection
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-service.yml

      - name: Verify deployment
        run: kubectl get pods

      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#all-tic-tac-toe'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
